### ISSUE TITLE
Trouble with resolving references

### ISSUE THREAD

**Issue by evelynhathaway** [ajv-validator/ajv-cli#107]
Hi there, I am trying to reference files and I am not getting it to work even with `-r`. The files that come from the below minimal reproduction work on my coworker's validation tests, but not in AJV.

**table.json**
```json
{
  "$id": "https://test.example.com/schemas/table",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "https://test.example.com/schemas/id#definitions/ID"
    }
  },
  "required": ["id"],
  "additionalProperties": false
}
```

**id.json**
```json
{
  "$id": "https://test.example.com/schemas/id",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "ID": {
      "type": "string"
    }
  }
}
```

```bash
# Fails
$ ajv compile -s './*.json'
schema ./repro/id.json is valid
schema ./repro/table.json is invalid
error: can't resolve reference https://test.example.com/schemas/id#definitions/ID from id https://test.example.com/schemas/table

# Fails
$ ajv compile -s './*.json' -r './id.json'
schema ./repro/id.json is invalid
error: schema with key or id "https://test.example.com/schemas/id" already exists
schema ./repro/table.json is invalid
error: can't resolve reference https://test.example.com/schemas/id#definitions/ID from id https://test.example.com/schemas/table

# Fails
$ ajv compile -s './table.json' -r './id.json'
schema ./repro/table.json is invalid
error: can't resolve reference https://test.example.com/schemas/id#definitions/ID from id https://test.example.com/schemas/table
```

I would appreciate any thoughts if this is indeed a AJV issue ❤️

**Comment by tsteinholz** [comment]
In your base ref, just use the name of the file (in the same directory). The `$ref` property is relative to the `$id` property.

In table.json
` "$ref": "id.json#definitions/ID"`

**Comment by evelynhathaway** [comment]
Thanks for your suggestion, but I am experiencing the same issue. I would like to use the URI IDs if possible as well.

```bash
$ npx ajv compile -s './table.json' -r './id.json'
schema ./table.json is invalid
error: can't resolve reference id.json#definitions/ID from id https://test.example.com/schemas/table
```

**Comment by tsteinholz** [comment]
I had a very similar issue and this guide helped me through it https://json-schema.org/understanding-json-schema/structuring.html#using-id-with-ref

I was trying to work with your schema but wasn't able to get it to compile either... not sure if there is another issue present there as well.

**Comment by epoberezkin** [comment]
The mistake in the schema is subtle but important: you need to use the reference `"https://test.example.com/schemas/id#/definitions/ID"` (in your reference `/` after `#` is missing)

You can also use relative URI there: `"id#/definitions/ID"` - it also works, see this repl: https://runkit.com/esp/60259d3c4491fe001a1cd0d6

**Comment by evelynhathaway** [comment]
That works! Oh my gosh thank you!
