### ISSUE TITLE
using with lint-staged and more than one file fails with "error: invalid syntax (too many arguments)"

### ISSUE THREAD

**Issue by pke** [ajv-validator/ajv-cli#126]
I have this lint-staged entry:

```
"changelog/*.{yaml,yml}": "ajv validate -s ./changelog/schema/changelog.schema.json -d"
```

which works fine as long as only one file is staged. When multiple files are staged and handed over to ajv-cli it quits with "error: invalid syntax (too many arguments)".

I guess its because lint-staged resolves the yml files to absolute paths and each of them would require a "-d " prefix for ajv-cli like so?

`ajv -d file1 -d file2`

Would it be possible to just accept input without the `-d` argument and treat any non-option as input path?

`ajv file1 file2`

**Comment by epoberezkin** [comment]
correct. -d can also accept glob pattern, but it's not how lint work.

I think it's better (=less work) to write a small bash script that accepts the list of args and passes them all to ajv-cli each with -d, than to support this flexibility in ajv-cli parameters - hope it makes sense...

There may be another use-case when you want to pass multiple schemas to compile each one - then you'd need to support the same with -s option - it would quickly get complex...

**Comment by pke** [comment]
Using this file:

```bash
#!/usr/bin/env bash

for file in "$@"; do
  ./node_modules/.bin/ajv validate -s ./changelog/schema/changelog.schema.json -d "$file"
done
```

and this lint-staged directive now:

```json
"lint-staged": {
   "changelog/*.{yaml,yml}": "scripts/lint-changelogs.sh"
}
```
