### ISSUE TITLE
Unable to reference ajv-formats

### ISSUE THREAD

**Issue by JaneJeon** [ajv-validator/ajv-cli#186]
ajv-cli by default screeches to a halt if it sees something like "format": "date" (god forbid).

I've been told that including https://github.com/ajv-validator/ajv-formats would be the answer; however, ajv-cli cannot include ajv-formats because of the way it's exported. e.g.: ajv -c ajv-formats compile -s $file fails...

**Comment by epoberezkin** [comment]
@JaneJeon how did you resolve?
