### ISSUE TITLE
strict mode: missing type "object" for keyword "additionalProperties" with draft7 schema

### ISSUE THREAD

**Issue by vish-kp** [ajv-validator/ajv-cli#187]
There's already an issue at https://github.com/ajv-validator/ajv-cli/issues/137 which was closed by you before we could have full clarity on the solution to the problem. So, I have created a new issue here.

additionalProperties field is supposed to be a boolean value where if the additionalProperties is set to true, we allow the json to have additional properties. ajv does not see it in this way but reads it as another property of the object that contains it which is why I feel is a bug.

If it is not a bug, would you please give us an example on how to implement additionalProperties as an object?

**Comment by epoberezkin** [comment]
Please do not create the duplicates - it's ok to raise the question in the closed issue (which was closed because it is an expected behaviour).

I further commented in the original issue.
