### ISSUE TITLE
ajv-cli can't see regex format in ajv-formats

### ISSUE THREAD

**Issue by pcolby** [ajv-validator/ajv-cli#188]
Not sure if this is something I'm doing wrong, or an issue in ajv-formats, or ajv-cli...?

I have:
```
$ npm -g list
/usr/local/lib
├── ajv-cli@5.0.0
├── ajv-formats@2.1.1
└── ajv@8.6.2
```
(and no local packages)

When I run as:
```
ajv -s ... -m ... -d ...
```
I get lots of unknown formats, as expected (I guess).

When I run add `-c ajv-formats` as:
```
ajv -c ajv-formats -s ... -m ... -d ...
```

I still get the following unknown formats:
```
unknown format "uri-reference" ignored in schema at path "#/properties/%24id"
unknown format "uri-reference" ignored in schema at path "#/properties/%24id"
unknown format "uri" ignored in schema at path "#/properties/%24schema"
unknown format "uri" ignored in schema at path "#/properties/%24schema"
unknown format "uri-reference" ignored in schema at path "#/properties/%24ref"
unknown format "uri-reference" ignored in schema at path "#/properties/%24ref"
unknown format "uri-reference" ignored in schema at path "#/properties/%24recursiveRef"
unknown format "uri-reference" ignored in schema at path "#/properties/%24recursiveRef"
unknown format "uri" ignored in schema at path "#/properties/%24vocabulary/propertyNames"
unknown format "uri" ignored in schema at path "#/properties/%24vocabulary/propertyNames"
unknown format "regex" ignored in schema at path "#/properties/patternProperties/propertyNames"
unknown format "regex" ignored in schema at path "#/properties/patternProperties/propertyNames"
unknown format "regex" ignored in schema at path "#/properties/pattern"
unknown format "regex" ignored in schema at path "#/properties/pattern"
```

I can see those formats are defined in the installed `ajv-formats` module. Is there some reason they wouldn't be being recognised by ajv-cli?

Thanks! 🙂

**Comment by proski** [comment]
There is an (almost) undocumented `-c` option (you need to know what to look for to find it). To enable format support, add `-c ajv-format` to the command line. I discovered that on https://stackoverflow.com/questions/66355820/how-to-make-ajv-cli-to-consider-formats (but first I gave up and I wrote my own CLI).

Obviously, it's still a bug. The default behavior should be functional. I like that AJV is strict by default, that's such a great contrast to other validators! So let me suggest this behavior:

- If ajv-format is installed and format checks are not disabled, use ajv-format.
- If ajv-format is not installed and format checks are not disabled, display a warning and disable format checks.
- If format checks are disabled, don't use ajv-format unless forced by the `-c` option.

**Comment by pcolby** [comment]
Thank @proski. Yep, as explained above, I am already using `-c ajv-formats`, which does help - without it, I also get warnings about unknown formats `uri` and `uuid`, eg:

```sh
ajv -s ... -m ... -d ... 2> without.txt
ajv -s ... -m ... -d ... -c ajv-formats 2> with.txt
diff without.txt with.txt
```

```diff
15,20d14
< unknown format "uri" ignored in schema at path "<redacted>/properties/schema"
< unknown format "uri" ignored in schema at path "<redacted>/properties/schema"
< unknown format "uuid" ignored in schema at path "#/properties/<redacted>"
< unknown format "uuid" ignored in schema at path "#/properties/<redacted>"
< unknown format "uri" ignored in schema at path "#/properties/<redacted>"
< unknown format "uri" ignored in schema at path "#/properties/<redacted>"
```

So it helps, but doesn't solve the problem. I'm using the (current) latest versions from npmjs:

```
├── ajv-cli@5.0.0
└── ajv-formats@2.1.1
```

And the [ajv-formats docs](https://www.npmjs.com/package/ajv-formats) specifically says it defines the `uri`, `uri-reference` and `regex` formats, so still not sure what I'm doing wrong.

Thanks! 🙂

**Comment by proski** [comment]
Sorry, I came to this page looking for my issue and neglected to read it carefully!

In my case, ajv-cli complains about formats in the schema I specify on the command line. In your case, it appears that ajv-cli is complaining about formats in the meta-schema while validating your schema.

I cannot reproduce your issue even if I downgrade ajv to version 8.6.2 (the current version is 8.11.0).

I suggest that you upgrade ajv anyway and retry. I'm afraid you removed too much context for others to reproduce this issue. Maybe you could make a minimal case and post it as is?

I'm posting the script I wrote as a replacement for ajv-cli with one change, it disables schema validation. See if it makes any difference for you. Try replacing false with true to see if it makes any difference.

```js
#!/usr/bin/env node

// Validate JSON document against JSON schema.
//
// Run "npm install ajv ajv-formats" to install the dependencies.
//
// Usage: validate_json_schema schema document

"use strict";

const fs = require("fs");
const Ajv = require("ajv");
const ajv = new Ajv({validateSchema: false});
const addFormats = require("ajv-formats");

addFormats(ajv);

if (process.argv.length !== 4) {
    console.log("Usage: validate_json_schema schema document");
    process.exit(2);
}

const schema_file = process.argv[2];
const schema = JSON.parse(fs.readFileSync(schema_file, "utf-8"));
const validator = ajv.compile(schema);

const document_file = process.argv[3];
const document = JSON.parse(fs.readFileSync(document_file, "utf-8"));

if (validator(document)) {
    console.log("Valid file");
    process.exit(0);
} else {
    console.log(validator.errors);
    process.exit(1);
}
```

**Comment by pcolby** [comment]
> In your case, it appears that ajv-cli is complaining about formats in the meta-schema while validating your schema.

That's an interesting observation. Indeed, the schemas and metaschemas all validate fine on their own, its only when they're used to validate sample data that the issue occurs. A minimal test case will likely help.

> the current version is 8.11.0 ... I suggest that you upgrade ajv anyway and retry.

The `ajv-cli` version I'm using already includes `ajv` 8.11.0

```
├─┬ ajv-cli@5.0.0
│ ├── ajv@8.11.0
│ └─┬ json-schema-migrate@2.0.0
│   └── ajv@8.11.0 deduped
├─┬ ajv-formats@2.1.1
│ └── ajv@8.11.0
```

> you removed too much context for others to reproduce this issue. Maybe you could make a minimal case and post it as is?

Yep, if there's no obvious problem (ie it _should_ work via `-c ajv-formats`), then I'll strip it down to bare-minimum, and share the result.

Thanks again 🙂

**Comment by pcolby** [comment]
Ah, ok, I've found the problem... I have a recursive meta-schema, which (based on Draft 7 capabilities) stated it's `$schema` property as itself, like:

```json
{
  "$id": "https://example.com/meta",
  "$schema": "https://example.com/meta",
  ...
}
```

Which worked fine (for the limitation so of the time). But, when updating to drafts 2019-09 (and then 2020-12), and using the new `$recursiveAnchor` (`$dynamicAnchor` in 2020-12) and `$vocabulary` keywords, it became like:

```json
{
  "$id": "https://example.com/meta",
  "$schema": "https://example.com/meta", # <- this was the problem.
  "$dynamicAnchor": "meta",
  "$vocabulary": {
    "https://json-schema.org/draft/2020-12/vocab/core": true,
    "https://json-schema.org/draft/2020-12/vocab/applicator": true,
    "https://json-schema.org/draft/2020-12/vocab/validation": true,
  },
  "allOf": [
    {"$ref": "https://json-schema.org/draft/2020-12/meta/core"},
    {"$ref": "https://json-schema.org/draft/2020-12/meta/applicator"},
    {"$ref": "https://json-schema.org/draft/2020-12/meta/validation"},
  ],
  ...
}
```
Which meant that, for this meta-schema, `ajv` was seeing the formats in the vocabularies, but actually had no definition for those formats in the context of this meta-schema, as the schema itself had not included the dynamic-anchor source.

So, at least for draft 2019-09 and 2020-12 recursive meta-schemas, the `$schema` should be the canonical draft schema URI.

Big thanks to @proski for helping me work this one through! 😄
