### ISSUE TITLE
Compiled validate function of schema for JSONSchema appears to be invalid

### ISSUE THREAD

**Issue by darcyparker** [ajv-validator/ajv-cli#20]
I am using [JSON schema's schema](http://json-schema.org/schema) renamed to `schema.json` to generate a validator:

``` bash
ajv compile -s ./schema.json -o jsonSchemaValidator.js
```

The output `jsonSchemaValidator.js` attempts to reference `refVal5.enum`.  But `refVal5` is undefined... so when I try to use the exported `validate` function I get an error about it being `undefined` regardless of the schema I pass to it.

For example in a node repl:

``` js
var validate = require('./jsonSchemaValidator');
var fs = require('fs')
var schemaString = fs.readFileSync('./schema.json', 'utf8');
validate(JSON.parse(schemaString));
```

And I get this exception:

```
ReferenceError: refVal5 is not defined
    at validate (/home/dparker/src/test/jsonSchemaValidator.js:1143:79)
    at validate (/home/dparker/src/test/jsonSchemaValidator.js:841:64)
    at repl:1:1
    at sigintHandlersWrap (vm.js:32:31)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInContext (vm.js:31:12)
    at REPLServer.defaultEval (repl.js:308:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:489:10)
```

> I did `npm install --save-dev ajv` so that the `validate` function can import `formats` and `equals`.

I am assuming compiling a validator for json schema should work and I am making a mistake. Any suggestions?

I don't see bugs about it in https://github.com/epoberezkin/ajv  Before I file a bug there I wanted to see if I am using the cli correctly. Thank you in advance for support/help.

**Comment by epoberezkin** [comment]
@darcyparker [ajv-pack](https://github.com/epoberezkin/ajv-pack) that is used to create standalone modules has quite a few limitations when it comes to referenced schemas. That's why it's "beta"... Please add this issue to ajv-pack together with the simplified schema  and data that lead to this error.

For now you will have to use ajv without precompiling the schema - it should work.

**Comment by darcyparker** [comment]
Thanks @epoberezkin - I will add this issue to ajv-pack too.

With regards to a simplified schema. I am not sure if you noticed, but the schema is the schema for JSON Schema itself.  My goal was to compile a validator for JSON schemas, so I was using the schema for JSON schema.  I am not sure where to begin to simplify the schema.

**Comment by epoberezkin** [comment]
Thank you. I understand now - you want to make a module for meta-schema validator. It will work at some point but I would not have too high expectations about it working very soon :) I'll be looking at it tomorrow, maybe it is not that difficult indeed.

**Comment by darcyparker** [comment]
I appreciate it - thanks. No worries if it takes longer.  I think there are other alternatives that may work for me.  But once I get it working for JSON schema's schema, I'd like to use this to plug into a typescript decorator that I can apply to a constructor/setter. (or similar...). That's the vision at least.

**Comment by epoberezkin** [comment]
@darcyparker you just have to use Ajv from code without precompiling the schema to the standalone module.

**Comment by epoberezkin** [comment]
Standalone validation code is now stable in Ajv v7 and the latest version of this CLI
