### ISSUE TITLE
Transfer to ajv-validator org

### ISSUE THREAD

**Issue by epoberezkin** [ajv-validator/ajv-cli#70]
@jessedc I hope you are well.

I would appreciate if you could move the repo to https://github.com/ajv-validator org - I hope you won't mind. I've moved all Ajv repos there from my account.

I am trying to address Ajv bus factor, and I think it would be easier to attract the maintainers by having Ajv & co in the org, rather than in my personal account.

Thanks a lot for starting this CLI utility - lots of people I know use it.

**Comment by jessedc** [comment]
No problem!

**Comment by jessedc** [comment]
@epoberezkin if you add me to the ajv-validator org and allow me to add repositories I will transfer it ASAP. :+1:

**Comment by epoberezkin** [comment]
Thank you - added!

**Comment by jessedc** [comment]
🚀

**Comment by epoberezkin** [comment]
Thank you :)
