### ISSUE TITLE
`nullable` keyword support

### ISSUE THREAD

**Issue by palemieux** [ajv-validator/ajv-cli#76]
ajv supports the `nullable` keyword from Open API 3 specification. Can this support be enabled using ajv-cli?

**Comment by epoberezkin** [comment]
Yes - PR is welcome

**Comment by epoberezkin** [comment]
It should be an additional CLI option that would be passed to Ajv

**Comment by epoberezkin** [comment]
in the last version that uses Ajv v7 nullable is supported by default
