### ISSUE TITLE
v4.0.0 format validation error

### ISSUE THREAD

**Issue by michaelheyman** [ajv-validator/ajv-cli#92]
## Description

On the latest version (`v4.0.0`), there are some new requirements regarding formats that I don't fully understand.

Some schemas that were valid before are invalid now.

## Example

schema.json

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Example with date-time",
  "type": "object",
  "properties": {
    "time": {
      "type": "string",
      "format": "date-time"
    }
  },
  "additionalProperties": false,
  "required": [
    "time"
  ]
}
```

example.json

```json
{
  "time": "2020-12-14T19:26:02Z"
}
```

Running with the previous version (`v3.3.0`), this schema is valid:

```bash
npx ajv-cli@3.3.0 validate -s schema.json -d example.json
npx: installed 47 in 3.748s
example.json valid
```

Running with the latest version (`v4.0.0`), this schema is invalid:

```bash
npx ajv-cli validate -s schema.json -d example.json
npx: installed 27 in 4.018s
schema schema.json is invalid
error: unknown format "date-time" ignored in schema at path "#/properties/time"
```

It was not clear to me from the new docs how to make formats known to `v4.0.0`. This example is using draft 7, which continues to be supported.

**Comment by epoberezkin** [comment]
You need to use parameter “-c ajv-formats” (and have ajv-formats installed).

**Comment by michaelheyman** [comment]
Ah, `ajv-formats` is a different dependency. I had tried it before and it couldn't find that package, naturally.

Was able to run this with

```bash
npx -p ajv-formats -p ajv-cli -c 'ajv validate -c ajv-formats -s schema.json -d example.json'
```

Thank you for your help.
