### ISSUE TITLE
ajv-4 produces invalid code

### ISSUE THREAD

**Issue by keean** [ajv-validator/ajv-cli#96]
ajv-4 fails to generate valid code, as it generates multiple definitions for the same function, which is causing a problem with Rollup. (ajv-3 worked fine on the same json schema file). I have enabled --code-lines to make the error readable:

1142: 
1143: 
1144: function validate26(data, {dataPath="", parentData, parentDataProperty, rootData=data}={}){
               ^
1145: let vErrors = null;
1146: let errors = 0;
SyntaxError: Identifier 'validate26' has already been declared (1144:9) in /...

In this case there are multiple definitions of "validate26". Initial inspection suggests that both definitions are identical, however it is still illegal to define the same function twice.

I am happy to help debug this, but I don't know what further information you might need.

**Comment by epoberezkin** [comment]
It's been [fixed in Ajv 7.0.2](https://github.com/ajv-validator/ajv/issues/1361) - please update (`npm update` should do it - or re-install).
